version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API=http://localhost:3000/api

  backend:
    build: ./backend
    ports:
      - "3005:3005"
    volumes:
      - backend-uploads:/app/uploads
    environment:
      - PORT=3005
      - MONGO_DB=${MONGO_DB}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - REFRESH_TOKEN=${REFRESH_TOKEN}

volumes:
  backend-uploads:
